image: node:10.1

cache:
  paths:
    - node_modules/

variables:
  PUBLIC_URL: "/property-listing" # slash is important

pages:
  stage: deploy
  environment: Stage
  only:
    - master
  before_script:
    #- npm i -g yarn

  script:
    - yarn install
    - yarn build
    - rm -rf public
    - cp -r build public/
    
  artifacts:
    paths:
    - public